# Authelia Users Database
# Passwords are argon2id hashed
# Default password for demo users: "password123"

users:
  admin:
    displayname: "Administrator"
    # password: password123 (hashed with argon2id)
    password: "$argon2id$v=19$m=65536,t=3,p=4$BnT5WqP3HGkLdWfL$7wnTWqzAGY3x3kBkl9WQWVl5LhUlWFVNpLqOXfGMIgE"
    email: admin@cortex.local
    groups:
      - admins
      - users

  demo:
    displayname: "Demo User"
    password: "$argon2id$v=19$m=65536,t=3,p=4$BnT5WqP3HGkLdWfL$7wnTWqzAGY3x3kBkl9WQWVl5LhUlWFVNpLqOXfGMIgE"
    email: demo@cortex.local
    groups:
      - users
